#!/usr/bin/env python3
"""Generate LanguagePlugin/language-pack.yml from embedded defaults."""
import yaml

PACK_VERSION = 2
MIN_LP_VERSION = "1.1.0"

LANGUAGE_PLUGIN = {
    "en": {
        "prefix": "&8[&7Language&8] &7",
        "only-player": "&c✘ &7Players only.",
        "usage-language": "&eUsage: &f/language <english|hebrew|french|spanish>",
        "language-set": "&a✔ &7Language set to &f{language}&7.",
        "language-unknown": "&c✘ &7Unknown language. Use: &fenglish, hebrew, french, spanish",
    },
    "he": {
        "prefix": "&8[&7שפה&8] &7",
        "only-player": "&c✘ &7לשחקנים בלבד.",
        "usage-language": "&eשימוש: &f/language <english|hebrew|french|spanish>",
        "language-set": "&a✔ &7השפה הוגדרה ל־&f{language}&7.",
        "language-unknown": "&c✘ &7שפה לא מוכרת. אפשר: &fenglish, hebrew, french, spanish",
    },
    "fr": {
        "prefix": "&8[&7Langue&8] &7",
        "only-player": "&c✘ &7Joueurs uniquement.",
        "usage-language": "&eUtilisation: &f/language <english|hebrew|french|spanish>",
        "language-set": "&a✔ &7Langue definie: &f{language}&7.",
        "language-unknown": "&c✘ &7Langue inconnue.",
    },
    "es": {
        "prefix": "&8[&7Idioma&8] &7",
        "only-player": "&c✘ &7Solo jugadores.",
        "usage-language": "&eUso: &f/language <english|hebrew|french|spanish>",
        "language-set": "&a✔ &7Idioma: &f{language}&7.",
        "language-unknown": "&c✘ &7Idioma desconocido.",
    },
}

HOME_PLUGIN = {
    "en": {
        "prefix": "&8[&b&lHOME&8] &7",
        "home-set": "&a✔ &7Home &f{home} &7saved.",
        "home-deleted": "&a✔ &7Home &f{home} &7deleted.",
        "home-not-found": "&c✘ &7Home &f{home} &7was not found.",
        "home-limit": "&c✘ &7You reached max homes: &f{max}&7.",
        "home-list-empty": "&eℹ &7You do not have any saved homes yet.",
        "home-list": "&b📍 &7Your homes: &f{list}",
        "teleport-start": "&b⌛ &7Teleporting to &f{home} &7in &f{seconds} &7seconds...",
        "teleported": "&a✔ &7Teleported to &f{home}&7.",
        "cooldown": "&c⏳ &7You can use this again in &f{remaining} &7seconds.",
        "teleport-cancelled-move": "&c✘ &7Teleport to &f{home} &7cancelled because you moved.",
        "only-player": "&c✘ &7This command is only for players.",
        "usage-sethome": "&eUsage: &f/sethome [name]",
        "usage-home": "&eUsage: &f/home [name]",
        "usage-delhome": "&eUsage: &f/delhome <name>",
        "invalid-home-name": "&c✘ &7Invalid home name. Use only: a-z, 0-9, _ or - (max 32).",
    },
    "he": {
        "prefix": "&8[&b&lHOME&8] &7",
        "home-set": "&a✔ &7הבית &f{home} &7נשמר בהצלחה.",
        "home-deleted": "&a✔ &7הבית &f{home} &7נמחק.",
        "home-not-found": "&c✘ &7לא נמצא בית בשם &f{home}&7.",
        "home-limit": "&c✘ &7הגעת למקסימום בתים: &f{max}&7.",
        "home-list-empty": "&eℹ &7עדיין אין לך בתים שמורים.",
        "home-list": "&b📍 &7הבתים שלך: &f{list}",
        "teleport-start": "&b⌛ &7משתגר אל &f{home} &7בעוד &f{seconds} &7שניות...",
        "teleported": "&a✔ &7הגעת אל &f{home}&7.",
        "cooldown": "&c⏳ &7אפשר להשתמש שוב בעוד &f{remaining} &7שניות.",
        "teleport-cancelled-move": "&c✘ &7השיגור אל &f{home} &7בוטל כי זזת.",
        "only-player": "&c✘ &7הפקודה זמינה רק לשחקנים.",
        "usage-sethome": "&eשימוש: &f/sethome [name]",
        "usage-home": "&eשימוש: &f/home [name]",
        "usage-delhome": "&eשימוש: &f/delhome <name>",
        "invalid-home-name": "&c✘ &7שם בית לא תקין. מותר רק a-z, 0-9, _ או - (עד 32 תווים).",
    },
    "fr": {
        "prefix": "&8[&b&lHOME&8] &7",
        "home-set": "&a✔ &7Le home &f{home} &7a ete enregistre.",
        "home-deleted": "&a✔ &7Le home &f{home} &7a ete supprime.",
        "home-not-found": "&c✘ &7Le home &f{home} &7est introuvable.",
        "home-limit": "&c✘ &7Vous avez atteint le maximum de homes: &f{max}&7.",
        "home-list-empty": "&eℹ &7Vous n'avez encore aucun home enregistre.",
        "home-list": "&b📍 &7Vos homes: &f{list}",
        "teleport-start": "&b⌛ &7Teleportation vers &f{home} &7dans &f{seconds} &7secondes...",
        "teleported": "&a✔ &7Teleporte vers &f{home}&7.",
        "cooldown": "&c⏳ &7Reessayez dans &f{remaining} &7secondes.",
        "teleport-cancelled-move": "&c✘ &7Teleportation vers &f{home} &7annulee car vous avez bouge.",
        "only-player": "&c✘ &7Commande reservee aux joueurs.",
        "usage-sethome": "&eUtilisation: &f/sethome [name]",
        "usage-home": "&eUtilisation: &f/home [name]",
        "usage-delhome": "&eUtilisation: &f/delhome <name>",
        "invalid-home-name": "&c✘ &7Nom de home invalide. Autorises: a-z, 0-9, _ ou - (max 32).",
    },
    "es": {
        "prefix": "&8[&b&lHOME&8] &7",
        "home-set": "&a✔ &7Home &f{home} &7guardado.",
        "home-deleted": "&a✔ &7Home &f{home} &7eliminado.",
        "home-not-found": "&c✘ &7No se encontro el home &f{home}&7.",
        "home-limit": "&c✘ &7Alcanzaste el maximo de homes: &f{max}&7.",
        "home-list-empty": "&eℹ &7Aun no tienes homes guardados.",
        "home-list": "&b📍 &7Tus homes: &f{list}",
        "teleport-start": "&b⌛ &7Teletransportando a &f{home} &7en &f{seconds} &7segundos...",
        "teleported": "&a✔ &7Teletransportado a &f{home}&7.",
        "cooldown": "&c⏳ &7Puedes usarlo de nuevo en &f{remaining} &7segundos.",
        "teleport-cancelled-move": "&c✘ &7El teletransporte a &f{home} &7se cancelo porque te moviste.",
        "only-player": "&c✘ &7Este comando es solo para jugadores.",
        "usage-sethome": "&eUso: &f/sethome [name]",
        "usage-home": "&eUso: &f/home [name]",
        "usage-delhome": "&eUso: &f/delhome <name>",
        "invalid-home-name": "&c✘ &7Nombre de home invalido. Solo: a-z, 0-9, _ o - (max 32).",
    },
}

TPA_PLUGIN = {
    "en": {
        "prefix": "&8[&d&lTPA&8] &7",
        "only-player": "&c✘ &7This command is only for players.",
        "usage-tpa": "&eUsage: &f/tpa <player>",
        "usage-tpahere": "&eUsage: &f/tpahere <player>",
        "player-not-found": "&c✘ &7Player &f{player} &7is not online.",
        "player-offline": "&c✘ &7The other player is no longer online.",
        "tpa-self": "&c✘ &7You cannot send a request to yourself.",
        "tpa-already-sent": "&c✘ &7You already have an outgoing request. Use &f/tpacancel&7.",
        "tpa-sent": "&a✔ &7Teleport request sent to &f{player}&7.",
        "tpa-received": "&b📨 &f{player} &7wants to teleport to you. &f/tpaccept &7or &f/tpdeny&7.",
        "tpahere-sent": "&a✔ &7Asked &f{player} &7to teleport to you.",
        "tpahere-received": "&b📨 &f{player} &7wants you to teleport to them. &f/tpaccept &7or &f/tpdeny&7.",
        "tpahere-accepted-target": "&a✔ &7You will teleport to &f{player}&7.",
        "tpahere-accepted-sender": "&a✔ &f{player} &7is teleporting to you.",
        "tpa-none-incoming": "&c✘ &7You have no incoming teleport requests.",
        "tpa-none-outgoing": "&c✘ &7You have no outgoing teleport request.",
        "tpa-accepted-target": "&a✔ &7You accepted &f{player}&7's request.",
        "tpa-accepted-sender": "&a✔ &f{player} &7accepted your request.",
        "tpa-denied-target": "&c✘ &7Request denied.",
        "tpa-denied-sender": "&c✘ &f{player} &7denied your teleport request.",
        "tpa-cancelled-sender": "&eℹ &7Your teleport request was cancelled.",
        "tpa-cancelled-target": "&eℹ &f{player} &7cancelled their teleport request.",
        "teleport-start": "&b⌛ &7Teleporting to &f{player} &7in &f{seconds} &7seconds...",
        "teleported": "&a✔ &7Teleported to &f{player}&7.",
        "teleport-cancelled-move": "&c✘ &7Teleport to &f{player} &7cancelled because you moved.",
        "cooldown": "&c⏳ &7You can send another request in &f{remaining} &7seconds.",
    },
    "he": {
        "prefix": "&8[&d&lTPA&8] &7",
        "only-player": "&c✘ &7הפקודה זמינה רק לשחקנים.",
        "usage-tpa": "&eשימוש: &f/tpa <player>",
        "usage-tpahere": "&eשימוש: &f/tpahere <player>",
        "player-not-found": "&c✘ &7השחקן &f{player} &7לא מחובר.",
        "player-offline": "&c✘ &7השחקן השני כבר לא מחובר.",
        "tpa-self": "&c✘ &7אי אפשר לשלוח בקשה לעצמך.",
        "tpa-already-sent": "&c✘ &7כבר יש לך בקשה פעילה. השתמש ב־&f/tpacancel&7.",
        "tpa-sent": "&a✔ &7בקשת שיגור נשלחה אל &f{player}&7.",
        "tpa-received": "&b📨 &f{player} &7רוצה להשתגר אליך. &f/tpaccept &7או &f/tpdeny&7.",
        "tpahere-sent": "&a✔ &7ביקשת מ־&f{player} &7להשתגר אליך.",
        "tpahere-received": "&b📨 &f{player} &7רוצה שתשתגר אליו. &f/tpaccept &7או &f/tpdeny&7.",
        "tpahere-accepted-target": "&a✔ &7תשתגר אל &f{player}&7.",
        "tpahere-accepted-sender": "&a✔ &f{player} &7משתגר אליך.",
        "tpa-none-incoming": "&c✘ &7אין לך בקשות שיגור נכנסות.",
        "tpa-none-outgoing": "&c✘ &7אין לך בקשת שיגור יוצאת.",
        "tpa-accepted-target": "&a✔ &7אישרת את הבקשה של &f{player}&7.",
        "tpa-accepted-sender": "&a✔ &f{player} &7אישר את הבקשה שלך.",
        "tpa-denied-target": "&c✘ &7הבקשה נדחתה.",
        "tpa-denied-sender": "&c✘ &f{player} &7דחה את בקשת השיגור שלך.",
        "tpa-cancelled-sender": "&eℹ &7בקשת השיגור שלך בוטלה.",
        "tpa-cancelled-target": "&eℹ &f{player} &7ביטל את בקשת השיגור.",
        "teleport-start": "&b⌛ &7משתגר אל &f{player} &7בעוד &f{seconds} &7שניות...",
        "teleported": "&a✔ &7הגעת אל &f{player}&7.",
        "teleport-cancelled-move": "&c✘ &7השיגור אל &f{player} &7בוטל כי זזת.",
        "cooldown": "&c⏳ &7אפשר לשלוח בקשה נוספת בעוד &f{remaining} &7שניות.",
    },
    "fr": {
        "prefix": "&8[&d&lTPA&8] &7",
        "only-player": "&c✘ &7Commande reservee aux joueurs.",
        "usage-tpa": "&eUtilisation: &f/tpa <player>",
        "usage-tpahere": "&eUtilisation: &f/tpahere <player>",
        "player-not-found": "&c✘ &7Le joueur &f{player} &7n'est pas en ligne.",
        "player-offline": "&c✘ &7L'autre joueur n'est plus en ligne.",
        "tpa-self": "&c✘ &7Vous ne pouvez pas vous envoyer une demande.",
        "tpa-already-sent": "&c✘ &7Vous avez deja une demande active. Utilisez &f/tpacancel&7.",
        "tpa-sent": "&a✔ &7Demande envoyee a &f{player}&7.",
        "tpa-received": "&b📨 &f{player} &7veut se teleporter vers vous. &f/tpaccept &7ou &f/tpdeny&7.",
        "tpahere-sent": "&a✔ &7Vous avez demande a &f{player} &7de venir vers vous.",
        "tpahere-received": "&b📨 &f{player} &7veut que vous vous teleportiez vers lui. &f/tpaccept &7ou &f/tpdeny&7.",
        "tpahere-accepted-target": "&a✔ &7Vous allez vous teleporter vers &f{player}&7.",
        "tpahere-accepted-sender": "&a✔ &f{player} &7se teleporte vers vous.",
        "tpa-none-incoming": "&c✘ &7Vous n'avez aucune demande entrante.",
        "tpa-none-outgoing": "&c✘ &7Vous n'avez aucune demande sortante.",
        "tpa-accepted-target": "&a✔ &7Vous avez accepte la demande de &f{player}&7.",
        "tpa-accepted-sender": "&a✔ &f{player} &7a accepte votre demande.",
        "tpa-denied-target": "&c✘ &7Demande refusee.",
        "tpa-denied-sender": "&c✘ &f{player} &7a refuse votre demande.",
        "tpa-cancelled-sender": "&eℹ &7Votre demande a ete annulee.",
        "tpa-cancelled-target": "&eℹ &f{player} &7a annule sa demande.",
        "teleport-start": "&b⌛ &7Teleportation vers &f{player} &7dans &f{seconds} &7secondes...",
        "teleported": "&a✔ &7Teleporte vers &f{player}&7.",
        "teleport-cancelled-move": "&c✘ &7Teleportation vers &f{player} &7annulee car vous avez bouge.",
        "cooldown": "&c⏳ &7Reessayez dans &f{remaining} &7secondes.",
    },
    "es": {
        "prefix": "&8[&d&lTPA&8] &7",
        "only-player": "&c✘ &7Este comando es solo para jugadores.",
        "usage-tpa": "&eUso: &f/tpa <player>",
        "usage-tpahere": "&eUso: &f/tpahere <player>",
        "player-not-found": "&c✘ &7El jugador &f{player} &7no esta en linea.",
        "player-offline": "&c✘ &7El otro jugador ya no esta en linea.",
        "tpa-self": "&c✘ &7No puedes enviarte una solicitud a ti mismo.",
        "tpa-already-sent": "&c✘ &7Ya tienes una solicitud activa. Usa &f/tpacancel&7.",
        "tpa-sent": "&a✔ &7Solicitud enviada a &f{player}&7.",
        "tpa-received": "&b📨 &f{player} &7quiere teletransportarse hacia ti. &f/tpaccept &7o &f/tpdeny&7.",
        "tpahere-sent": "&a✔ &7Pediste a &f{player} &7que se teletransporte hacia ti.",
        "tpahere-received": "&b📨 &f{player} &7quiere que te teletransportes hacia el. &f/tpaccept &7o &f/tpdeny&7.",
        "tpahere-accepted-target": "&a✔ &7Te teletransportaras a &f{player}&7.",
        "tpahere-accepted-sender": "&a✔ &f{player} &7se esta teletransportando hacia ti.",
        "tpa-none-incoming": "&c✘ &7No tienes solicitudes entrantes.",
        "tpa-none-outgoing": "&c✘ &7No tienes una solicitud saliente.",
        "tpa-accepted-target": "&a✔ &7Aceptaste la solicitud de &f{player}&7.",
        "tpa-accepted-sender": "&a✔ &f{player} &7acepto tu solicitud.",
        "tpa-denied-target": "&c✘ &7Solicitud denegada.",
        "tpa-denied-sender": "&c✘ &f{player} &7rechazo tu solicitud.",
        "tpa-cancelled-sender": "&eℹ &7Tu solicitud fue cancelada.",
        "tpa-cancelled-target": "&eℹ &f{player} &7cancelo su solicitud.",
        "teleport-start": "&b⌛ &7Teletransportando a &f{player} &7en &f{seconds} &7segundos...",
        "teleported": "&a✔ &7Teletransportado a &f{player}&7.",
        "teleport-cancelled-move": "&c✘ &7El teletransporte a &f{player} &7se cancelo porque te moviste.",
        "cooldown": "&c⏳ &7Puedes enviar otra solicitud en &f{remaining} &7segundos.",
    },
}


def plugin_messages(data):
    return {
        "minLanguagePluginVersion": MIN_LP_VERSION,
        "messages": data,
    }


pack = {
    "packVersion": PACK_VERSION,
    "messages": LANGUAGE_PLUGIN,
    "pluginSupport": {
        "HomePlugin": {"minLanguagePluginVersion": MIN_LP_VERSION},
        "TpaPlugin": {"minLanguagePluginVersion": MIN_LP_VERSION},
    },
    "pluginMessages": {
        "HomePlugin": plugin_messages(HOME_PLUGIN),
        "TpaPlugin": plugin_messages(TPA_PLUGIN),
    },
}

out = """# Remote language pack for LanguagePlugin
# Edit and publish to the URL in plugins/LanguagePlugin/config.yml

"""
out += yaml.dump(
    pack,
    allow_unicode=True,
    default_flow_style=False,
    sort_keys=False,
    width=120,
)

path = __file__.replace("scripts/generate-language-pack.py", "LanguagePlugin/language-pack.yml")
with open(path, "w", encoding="utf-8") as f:
    f.write(out)
print("Wrote", path, "bytes", len(out))
